# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/classify.ipynb.

# %% auto 0
__all__ = ['XGBClassifier']

# %% ../nbs/classify.ipynb 2
import pickle
from . import dataset

class XGBClassifier():
    
    def __init__(self, file_name):
        self.xgb_model = pickle.load(open(file_name, "rb"))
        self.feature_gen = dataset.FeatureGenerator([], 'all_data')
        
    def predict(self, img):
        img = dataset.load_image(img)
        if img is None:
            return None
        f = self.feature_gen.generate_features(img, include_generic=True)
        return self.xgb_model.predict([f])[0]
